/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import datadog.trace.api.Trace;

import datadog.trace.api.DDTags;
import io.opentracing.Scope;
import io.opentracing.Span;
import io.opentracing.Tracer;
import io.opentracing.util.GlobalTracer;

public class App {
    @Trace()
    public String getGreeting() {
        return "Hello World!";
    }

    @Trace()
    public String getGoodbye() {
        Tracer tracer = GlobalTracer.get();
        Span span = tracer.buildSpan("manual.operation")
                .withTag(DDTags.SERVICE_NAME, "sqlserver")
                .withTag(DDTags.RESOURCE_NAME, "GET /health")
                .start();
        try (Scope scope = tracer.activateSpan(span)) {
            // Alternatively, set tags after creation
            Thread.sleep(35);
        } catch (Exception e) {
            // Set error on span
        } finally {
            // Close span in a finally block
            span.finish();
        }
        return "Goodbye World!";
    }

    @Trace()
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new App().getGoodbye());
    }
}
