/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;
import datadog.trace.api.Trace;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    @Trace()
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
